name: README Badges Sync
on:
    workflow_dispatch:
    schedule:
        - cron: '0 8 * * 1' # every Monday at 08:00 UTC
permissions:
    contents: write
jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: npm i -g readme-badges-sync
            - run: readme-badges-sync
            - name: Commit changes
              run: |
                  if [[ -n $(git status --porcelain) ]]; then
                    git config user.name "github-actions[bot]"
                    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                    git add README.md
                    git commit -m "chore(readme): sync badges"
                    git push
                  fi
